### ISSUE TITLE
data length?

### ISSUE THREAD

**Issue by tomByrer** [kuon/js-base24#2]
> data length must be multiple of 32 bits

~ https://www.kuon.ch/post/2020-02-27-base24/

But in your code, you ask for [length 4](https://github.com/kuon/js-base24/blob/master/index.js#L26) & [length 7](https://github.com/kuon/js-base24/blob/master/index.js#L58).  I'm confused why, or maybe your docs are outdated?

I might learn a new language on my free time, either [Nim](https://nim-lang.org/) or [V](https://vlang.io/) & thought this might be neat to try out there.

TIA!

**Comment by kuon** [comment]
Hello, length is in byte in the code (8bit).

32 bit input (4 bytes) is transformed into a 7 bytes output.
